spring:
  config:
    import: application-secrets.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/library
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
  mvc:
    hidden-method:
      filter:
        enabled: true
  logging:
    level:
        root: INFO
        org:
            hibernate: INFO
            springframework: DEBUG
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
